### ISSUE TITLE
Passwords to both crypto & monitor users available for direct connections

### ISSUE THREAD

**Issue by jirislav** [ClickHouse/CryptoHouse#15]
The HTTP requests sent by the browser from the https://crypto.clickhouse.com UI contain access credentials of the `crypto` user. I don't want to expose exactly how as this issue cannot be marked sensitive.

But once the password of the `crypto` user is obtained, you have access to the `monitor` user as well, see [here why](https://github.com/ClickHouse/CryptoHouse/blob/main/setup.sql#L579). I'm not specific on purpose.

Anyone then has access either with the rate-limited `crypto` user or with the unlimited `monitor` user:

![image](https://github.com/user-attachments/assets/95e1aef6-99a5-4cf7-9176-3519d6c61fb8)

I would suggest these action items:
1. Make sure the browser doesn't need to know the password at all.
2. Change passwords for both users.
3. Rate limit the `monitor` user as well.

**Comment by gingerwizard** [comment]
@jirislav this is intentional. The crypto user is rate limited and quota'd -we expose these credentials for users to connect directly in via the client.

The monitor user can only read 100 rows per request. It also has a quota (much higher).

**Comment by jirislav** [comment]
Oh sorry, I should have read the README first 😅.

Btw, I don't see the `CREATE QUOTA monitor` query [in the SQL definition](https://github.com/ClickHouse/CryptoHouse/blob/main/setup.sql#L600), do you think it would be worth adding it there?

**Comment by gingerwizard** [comment]
Ah well spotted @jirislav ill add thanks!
