### ISSUE TITLE
CryptoHouse unreachable from SQL playground blogpost

### ISSUE THREAD

**Issue by Blargian** [ClickHouse/CryptoHouse#18]
**Describe the bug**

The link to CryptoHouse in the [Announcing the new ClickHouse SQL Playground](https://clickhouse.com/blog/announcing-the-new-sql-playground) is to `https://cryto.clickhouse.com/` and not `https://crypto.clickhouse.com/` and therefore can't be reached sadly.

**Comment by gingerwizard** [comment]
Fixed Thanks @Blargian
